"""
Functional tests for the reconciliation framework.

Tests run against local PySpark + Delta, using synthetic data
generated by the data_generator module.
"""

from __future__ import annotations

import os
import tempfile
from datetime import date

import pytest

pyspark = pytest.importorskip("pyspark", reason="PySpark not installed")

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

from recon.config import ReconcileConfig
from recon.helpers import get_spark, build_column_groups
from recon.runner import run_reconciliation


@pytest.fixture(scope="module")
def test_env(local_spark, tmp_path_factory):
    """Set up test data and config for functional tests."""
    from tests.data_generator import generate_test_data, inject_differences

    spark = local_spark
    base_dir = str(tmp_path_factory.mktemp("functional"))
    output_dir = os.path.join(base_dir, "recon_output")
    os.makedirs(output_dir, exist_ok=True)

    # Generate small test data: 3 quarters, 1000 rows/qtr, 10 numeric + 3 string cols
    left_path, right_path, critical_cols = generate_test_data(
        spark=spark,
        output_path=base_dir,
        n_quarters=3,
        base_rows_per_quarter=1000,
        rows_per_quarter_increment=0,
        n_numeric_cols=10,
        n_string_cols=3,
        n_date_cols=2,
        n_bool_cols=2,
        seed=42,
    )

    # Register as temp views for Spark SQL access
    spark.read.format("delta").load(left_path).createOrReplaceTempView("test_left")
    spark.read.format("delta").load(right_path).createOrReplaceTempView("test_right")

    # Create test output database
    spark.sql("CREATE DATABASE IF NOT EXISTS recon_test_db")

    return {
        "spark": spark,
        "base_dir": base_dir,
        "output_dir": output_dir,
        "left_path": left_path,
        "right_path": right_path,
        "critical_cols": critical_cols,
    }


class TestIdenticalTables:
    """When left and right tables are identical, expect zero mismatches."""

    def test_all_quarters_identical(self, test_env, local_spark):
        """All quarters should be marked identical with zero mismatches."""
        spark = local_spark

        cfg = ReconcileConfig(
            left_table_name="test_left",
            right_table_name="test_right",
            output_catalog="spark_catalog",
            output_schema="recon_test_db",
            key_cols=["policy_id", "quarter_date"],
            qtr_col="quarter_date",
            critical_cols=test_env["critical_cols"],
            all_feature_cols=test_env["critical_cols"],
            run_id="test_identical_001",
            source_label="TEST",
            detail_mode="sample",
            cleanup_tmp_tables=True,
        )

        outputs = run_reconciliation(cfg)

        # Verify quarter checksums: all identical
        checksums = spark.table(outputs["quarter_checksums"]).filter(
            F.col("run_id") == "test_identical_001"
        ).collect()
        assert len(checksums) == 3  # 3 quarters
        for row in checksums:
            assert row["quarter_status"] == "identical"

        # Verify column summary: all zeros
        col_summary = spark.table(outputs["column_summary_all_quarters"]).filter(
            F.col("run_id") == "test_identical_001"
        ).collect()
        assert len(col_summary) > 0
        for row in col_summary:
            assert row["mismatch_count"] == 0
            assert row["null_mismatch_count"] == 0


class TestRowDifferences:
    """Test detection of left_only and right_only rows."""

    def test_added_removed_rows(self, test_env, local_spark):
        """Inject row additions and removals, verify correct counts."""
        from tests.data_generator import inject_differences

        spark = local_spark
        base_dir = test_env["base_dir"]

        # Create modified right table with 10 added rows, 5 removed
        modified_path = inject_differences(
            spark=spark,
            source_path=test_env["left_path"],
            output_path=os.path.join(base_dir, "right_modified_rows"),
            change_rate=0.0,  # No value changes
            add_rows=10,
            remove_rows=5,
            seed=99,
        )
        spark.read.format("delta").load(modified_path).createOrReplaceTempView("test_right_rows")

        cfg = ReconcileConfig(
            left_table_name="test_left",
            right_table_name="test_right_rows",
            output_catalog="spark_catalog",
            output_schema="recon_test_db",
            key_cols=["policy_id", "quarter_date"],
            qtr_col="quarter_date",
            critical_cols=test_env["critical_cols"],
            all_feature_cols=test_env["critical_cols"],
            run_id="test_rows_001",
            source_label="TEST",
            detail_mode="sample",
            cleanup_tmp_tables=True,
        )

        outputs = run_reconciliation(cfg)

        # Check row status counts
        row_counts = spark.table(outputs["row_status_counts"]).filter(
            F.col("run_id") == "test_rows_001"
        ).collect()

        status_map = {}
        for row in row_counts:
            status = row["row_status"]
            status_map[status] = status_map.get(status, 0) + row["row_count"]

        # Should have left_only (removed) and right_only (added) rows
        assert status_map.get("left_only", 0) == 5
        assert status_map.get("right_only", 0) == 10


class TestColumnMismatches:
    """Test detection of value-level differences."""

    def test_numeric_mismatches(self, test_env, local_spark):
        """Inject numeric value changes, verify mismatch detection."""
        from tests.data_generator import inject_differences

        spark = local_spark
        base_dir = test_env["base_dir"]
        critical_cols = test_env["critical_cols"]

        # Change 10% of rows in first 3 numeric columns
        target_cols = critical_cols[:3]
        modified_path = inject_differences(
            spark=spark,
            source_path=test_env["left_path"],
            output_path=os.path.join(base_dir, "right_modified_values"),
            change_rate=0.10,
            change_cols=target_cols,
            seed=77,
        )
        spark.read.format("delta").load(modified_path).createOrReplaceTempView("test_right_values")

        cfg = ReconcileConfig(
            left_table_name="test_left",
            right_table_name="test_right_values",
            output_catalog="spark_catalog",
            output_schema="recon_test_db",
            key_cols=["policy_id", "quarter_date"],
            qtr_col="quarter_date",
            critical_cols=critical_cols,
            all_feature_cols=critical_cols,
            run_id="test_values_001",
            source_label="TEST",
            detail_mode="sample",
            cleanup_tmp_tables=True,
        )

        outputs = run_reconciliation(cfg)

        # Check column summary: modified columns should have mismatches
        col_summary = spark.table(outputs["column_summary_all_quarters"]).filter(
            F.col("run_id") == "test_values_001"
        ).collect()

        summary_map = {row["column"]: row for row in col_summary}

        # Modified columns should have mismatches > 0
        for col in target_cols:
            assert col in summary_map, f"{col} not in summary"
            assert summary_map[col]["mismatch_count"] > 0, f"{col} should have mismatches"

        # Unmodified columns should have zero mismatches
        unmodified = [c for c in critical_cols if c not in target_cols]
        for col in unmodified:
            if col in summary_map:
                assert summary_map[col]["mismatch_count"] == 0, f"{col} should have no mismatches"


class TestTolerance:
    """Test that numeric tolerance suppresses small differences."""

    def test_within_tolerance(self, test_env, local_spark):
        """Small numeric diffs within tolerance should not be flagged."""
        from tests.data_generator import inject_differences
        import random

        spark = local_spark
        base_dir = test_env["base_dir"]
        critical_cols = test_env["critical_cols"]

        # Inject very small changes (within tolerance of 1.0)
        target_cols = [critical_cols[0]]

        # Read source, add tiny noise
        left_df = spark.read.format("delta").load(test_env["left_path"])
        rows = left_df.collect()
        schema = left_df.schema

        rng = random.Random(55)
        modified_rows = []
        for r in rows:
            d = r.asDict()
            if d[target_cols[0]] is not None:
                d[target_cols[0]] = d[target_cols[0]] + rng.uniform(-0.5, 0.5)  # within 1.0 tolerance
            modified_rows.append(tuple(d[f.name] for f in schema.fields))

        tol_path = os.path.join(base_dir, "right_tolerance")
        spark.createDataFrame(modified_rows, schema=schema).write.format("delta").mode("overwrite").save(tol_path)
        spark.read.format("delta").load(tol_path).createOrReplaceTempView("test_right_tol")

        cfg = ReconcileConfig(
            left_table_name="test_left",
            right_table_name="test_right_tol",
            output_catalog="spark_catalog",
            output_schema="recon_test_db",
            key_cols=["policy_id", "quarter_date"],
            qtr_col="quarter_date",
            critical_cols=critical_cols,
            all_feature_cols=target_cols,
            run_id="test_tol_001",
            source_label="TEST",
            default_numeric_tolerance=1.0,
            detail_mode="sample",
            cleanup_tmp_tables=True,
        )

        outputs = run_reconciliation(cfg)

        # Column should show zero mismatches because diffs are within tolerance
        col_summary = spark.table(outputs["column_summary_all_quarters"]).filter(
            (F.col("run_id") == "test_tol_001") & (F.col("column") == target_cols[0])
        ).collect()

        if col_summary:
            assert col_summary[0]["mismatch_count"] == 0


class TestMismatchSample:
    """Test that mismatch samples are correctly produced."""

    def test_sample_output(self, test_env, local_spark):
        """Verify mismatch_sample table contains expected rows."""
        from tests.data_generator import inject_differences

        spark = local_spark
        base_dir = test_env["base_dir"]
        critical_cols = test_env["critical_cols"]

        # Inject changes in first column
        target_cols = [critical_cols[0]]
        modified_path = inject_differences(
            spark=spark,
            source_path=test_env["left_path"],
            output_path=os.path.join(base_dir, "right_sample_test"),
            change_rate=0.20,
            change_cols=target_cols,
            seed=88,
        )
        spark.read.format("delta").load(modified_path).createOrReplaceTempView("test_right_sample")

        cfg = ReconcileConfig(
            left_table_name="test_left",
            right_table_name="test_right_sample",
            output_catalog="spark_catalog",
            output_schema="recon_test_db",
            key_cols=["policy_id", "quarter_date"],
            qtr_col="quarter_date",
            critical_cols=critical_cols,
            all_feature_cols=target_cols,
            run_id="test_sample_001",
            source_label="TEST",
            detail_mode="sample",
            sample_per_column=5,
            cleanup_tmp_tables=True,
        )

        outputs = run_reconciliation(cfg)

        # Check mismatch_sample exists and has samples
        samples = spark.table(outputs["mismatch_sample"]).filter(
            F.col("run_id") == "test_sample_001"
        ).collect()

        assert len(samples) > 0
        # Should not exceed sample_per_column per quarter per column
        # With 3 quarters and 1 column: max = 3 * 5 = 15
        assert len(samples) <= 15
